name: twilio_programmable_video_example
description: Demonstrates how to use the twilio_programmable_video plugin.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  cloud_functions: ^4.0.3
  collection: ^1.15.0-nullsafety.4
  cupertino_icons: ^1.0.2
  device_info: ^2.0.2
  enum_to_string: ^2.0.1
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.17.0
  native_device_orientation: ^1.0.0
  provider: ^5.0.0
  recase: ^4.0.0
  rxdart: ^0.27.1
  uuid: ^3.0.4
  wakelock: ^0.5.6
  # twilio_programmable_video:
  # twilio_programmable_video:
  #   path: ../
  twilio_programmable_video:
    git:
      url: https://github.com/Mangielijah/twilio.git
      ref: main # branch name


dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true
