// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3NgpWJKTO92ixsguSyzrCxgQmuRn5CuU',
    appId: '1:462709419415:web:5312417f64404a97eb68d2',
    messagingSenderId: '462709419415',
    projectId: 'twilio-video-663a9',
    authDomain: 'twilio-video-663a9.firebaseapp.com',
    databaseURL: 'https://twilio-video-663a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twilio-video-663a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAVjMzj1qZY05ry0BrzItKJ9x52BuEVM',
    appId: '1:462709419415:ios:54ebb46c18ff3ebeeb68d2',
    messagingSenderId: '462709419415',
    projectId: 'twilio-video-663a9',
    databaseURL: 'https://twilio-video-663a9-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'twilio-video-663a9.appspot.com',
    iosClientId: '462709419415-35q947t3uoqufhvundg9vf2foc55da1v.apps.googleusercontent.com',
    iosBundleId: 'twilio.flutter.ProgrammableVideoExampleMm',
  );
}
